default['mysql']['username'] = 'username'
default['mysql']['password'] = 'password'
default['mysql']['database']['dev'] = 'fuel_dev'
default['mysql']['database']['stg'] = 'fuel_stg'
default['mysql']['database']['prod'] = 'fuel_prod'
default['mysql']['database']['test'] = 'fuel_test'